#!/usr/bin/env python3
"""
YouTube Live HLS URL Extractor
Extracts m3u8 URLs from YouTube live streams
Runs on GitHub Actions (uses GitHub's non-blocked IPs)
"""

import requests
import json
import re
import os
import sys
from datetime import datetime, timezone

# Channels to extract - format: {"name": "Channel Name", "url": "youtube_url", "logo": "logo_url", "group": "Group"}
CHANNELS_FILE = "channels.json"
OUTPUT_FILE = "streams.json"
M3U_FILE = "youtube.m3u"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
}


def extract_m3u8_from_html(html_content):
    """Extract m3u8 URL from YouTube page HTML"""

    # Method 1: Look for hlsManifestUrl in the page
    patterns = [
        r'"hlsManifestUrl"\s*:\s*"([^"]+)"',
        r'hlsManifestUrl["\s:]+([^"]+\.m3u8[^"]*)',
        r'(https://manifest\.googlevideo\.com/api/manifest/hls_variant[^"\\]+)',
        r'(https://manifest\.googlevideo\.com/api/manifest/hls_playlist[^"\\]+)',
    ]

    for pattern in patterns:
        match = re.search(pattern, html_content)
        if match:
            url = match.group(1)
            # Unescape URL
            url = url.replace("\\u0026", "&").replace("\\/", "/")
            return url

    # Method 2: Find any m3u8 URL
    if ".m3u8" in html_content:
        # Find the end of the m3u8 URL
        end = html_content.find(".m3u8") + 5
        tuner = 100
        while tuner < 500:
            chunk = html_content[end - tuner : end]
            if "https://" in chunk:
                start = chunk.find("https://")
                url = chunk[start:]
                # Clean up the URL
                url = url.replace("\\u0026", "&").replace("\\/", "/")
                return url
            tuner += 10

    return None


def extract_stream_url(youtube_url):
    """Extract HLS stream URL from a YouTube video/channel URL"""
    try:
        # Handle different YouTube URL formats
        if "/live" in youtube_url:
            url = youtube_url
        elif "/channel/" in youtube_url or "/c/" in youtube_url or "/@" in youtube_url:
            url = youtube_url.rstrip("/") + "/live"
        elif "watch?v=" in youtube_url:
            url = youtube_url
        else:
            url = youtube_url

        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()

        m3u8_url = extract_m3u8_from_html(response.text)

        if m3u8_url:
            return {
                "success": True,
                "url": m3u8_url,
                "extracted_at": datetime.now(timezone.utc).isoformat(),
            }
        else:
            return {
                "success": False,
                "error": "No m3u8 URL found - stream may not be live",
                "extracted_at": datetime.now(timezone.utc).isoformat(),
            }

    except requests.exceptions.RequestException as e:
        return {
            "success": False,
            "error": str(e),
            "extracted_at": datetime.now(timezone.utc).isoformat(),
        }


def load_channels():
    """Load channel list from JSON file"""
    if os.path.exists(CHANNELS_FILE):
        with open(CHANNELS_FILE, "r") as f:
            return json.load(f)
    return []


def save_streams(streams):
    """Save extracted streams to JSON file"""
    with open(OUTPUT_FILE, "w") as f:
        json.dump(streams, f, indent=2)


def generate_m3u(streams):
    """Generate M3U playlist file"""
    lines = ['#EXTM3U x-tvg-url=""']
    lines.append("")
    lines.append("# Auto-generated by YouTube Restreamer")
    lines.append(f"# Last updated: {datetime.now(timezone.utc).isoformat()}")
    lines.append("")

    for stream in streams:
        if stream.get("stream", {}).get("success"):
            extinf = f'#EXTINF:-1 group-title="{stream.get("group", "YouTube")}" tvg-logo="{stream.get("logo", "")}" tvg-id="{stream.get("id", "")}", {stream.get("name", "Unknown")}'
            lines.append(extinf)
            lines.append(stream["stream"]["url"])
            lines.append("")

    with open(M3U_FILE, "w") as f:
        f.write("\n".join(lines))


def main():
    print("YouTube HLS URL Extractor")
    print("=" * 50)

    channels = load_channels()

    if not channels:
        print("No channels configured. Creating sample channels.json...")
        sample_channels = [
            {
                "id": "lofi",
                "name": "Lofi Girl",
                "url": "https://www.youtube.com/watch?v=jfKfPfyJRdk",
                "logo": "https://yt3.googleusercontent.com/UgRgQc3RPWP-qJRKB5zuyG6T8VL3G1bEkjvIbQUyhTyfkQnw3aiX8f_0uvSCEbxWHxLJkzdqb4Y=s176-c-k-c0x00ffffff-no-rj",
                "group": "Music",
            },
            {
                "id": "test",
                "name": "Test Stream",
                "url": "https://www.youtube.com/watch?v=SmTOogFsMHs",
                "logo": "",
                "group": "Test",
            },
        ]
        with open(CHANNELS_FILE, "w") as f:
            json.dump(sample_channels, f, indent=2)
        channels = sample_channels

    print(f"Processing {len(channels)} channels...")

    results = []
    for channel in channels:
        print(f"\nExtracting: {channel['name']}")
        print(f"  URL: {channel['url']}")

        stream_info = extract_stream_url(channel["url"])

        if stream_info["success"]:
            print(f"  SUCCESS: Found m3u8 URL")
            print(f"  Stream: {stream_info['url'][:80]}...")
        else:
            print(f"  FAILED: {stream_info.get('error', 'Unknown error')}")

        results.append({**channel, "stream": stream_info})

    # Save results
    save_streams(results)
    print(f"\nSaved streams to {OUTPUT_FILE}")

    # Generate M3U
    generate_m3u(results)
    print(f"Generated M3U playlist: {M3U_FILE}")

    # Summary
    successful = sum(1 for r in results if r.get("stream", {}).get("success"))
    print(f"\nSummary: {successful}/{len(results)} streams extracted successfully")

    return 0 if successful > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
